# Generated by Django 4.0.2 on 2022-09-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Name',
            new_name='Email',
        ),
    ]
