# Generated by Django 4.0.2 on 2022-09-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermaster_rename_name_admin_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Name',
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster'),
        ),
        migrations.AddField(
            model_name='book',
            name='bname',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster'),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
