# Generated by Django 4.0.2 on 2022-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_email_usermaster_email_remove_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bname',
            field=models.CharField(max_length=100),
        ),
    ]
