# Generated by Django 4.0.2 on 2022-09-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_bname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bname',
            new_name='Name',
        ),
    ]
