# Generated by Django 4.0.2 on 2022-09-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_book_bname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_id',
        ),
    ]
