# Generated by Django 4.0.2 on 2022-09-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_usermaster_is_active_usermaster_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='Email',
            new_name='email',
        ),
    ]
