# Generated by Django 4.0.2 on 2022-09-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_email_usermaster_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='is_verified',
        ),
    ]
