# Generated by Django 4.0.2 on 2022-09-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_usermaster_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Cpassword',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Cpassword',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Password',
            new_name='password',
        ),
    ]
